language: cpp

# reduce clone time by only getting the latest commit and not the whole history (default for travis is 100)
git:
  depth: 1

# only run travis on the master branch
branches:
  only:
  - master

# do not build with clang until fixed
compiler:
  - gcc
#  - clang

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libbz2-dev cmake libncurses5-dev libmysqlclient-dev libreadline-dev libsdl1.2-dev libssl-dev zlib1g-dev libace-dev  build-essential

script:
 - mkdir build
 - ls
 - cd build
 - cmake -DCMAKE_BUILD_TYPE=Debug ../cmake
 - sudo make -j4
 